theme: jekyll-theme-architect
title: Chandra Sivaraman
description: Software Engineering Notes
copyright: © 2020 Chandra Sivaraman
permalink: pretty
markdown: kramdown
highlighter: rouge 
kramdown:
  input: GFM
